### PR TITLE
Fixes IllegalStateException

### LINKED ISSUE #355: JarFileModule cannot be added to scope
When using [AndroidAnalysisScope.setupAndroidAnalysisScope](https://github.com/wala/WALA/blob/master/com.ibm.wala.dalvik/src/com/ibm/wala/dalvik/util/AndroidAnalysisScope.javal) to set up the scope with a Java Library for the androidLib argument, e.g. the Android SDK jar I receive the following exception:
`[FATAL EXCEPTION] analysis aborted: zip file closed
java.lang.IllegalStateException: zip file closed
  at java.util.zip.ZipFile.ensureOpen(java.base@9-internal/ZipFile.java:639)
  at java.util.zip.ZipFile.access$500(java.base@9-internal/ZipFile.java:73)
  at java.util.zip.ZipFile$ZipEntryIterator.<init>(java.base@9-internal/ZipFile.java:467)
  at java.util.zip.ZipFile.entries(java.base@9-internal/ZipFile.java:507)
  at java.util.jar.JarFile.access$401(java.base@9-internal/JarFile.java:132)
  at java.util.jar.JarFile$JarEntryIterator.<init>(java.base@9-internal/JarFile.java:537)
  at java.util.jar.JarFile$JarEntryIterator.<init>(java.base@9-internal/JarFile.java:534)
  at java.util.jar.JarFile.entries(java.base@9-internal/JarFile.java:609)
  at com.ibm.wala.classLoader.JarFileModule.getEntries(JarFileModule.java:66)
  at com.ibm.wala.classLoader.ClassLoaderImpl.getClassFiles(ClassLoaderImpl.java:157)
  at com.ibm.wala.classLoader.ClassLoaderImpl.init(ClassLoaderImpl.java:504)
  at com.ibm.wala.dalvik.classLoader.WDexClassLoaderImpl.init(WDexClassLoaderImpl.java:100)
  at com.ibm.wala.classLoader.ClassLoaderFactoryImpl.makeNewClassLoader(ClassLoaderFactoryImpl.java:115)
  at com.ibm.wala.classLoader.ClassLoaderFactoryImpl.getLoader(ClassLoaderFactoryImpl.java:69)
  at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:259)
  at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:201)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:70)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:59)
  at com.ibm.wala.ipa.cha.ClassHierarchyFactory.make(ClassHierarchyFactory.java:32)
  at de.infsec.tpl.LibraryIdentifier.createClassHierarchy(LibraryIdentifier.java:108)`

The reasons seems to be this try-with-resources construct with the creation of the JarFileModule in the body:
`try (final JarFile jar = new JarFile(new File(al))) {
   scope.addToScope(ClassLoaderReference.Primordial, new JarFileModule(jar));
}`

Moving the new JarFileModule into the try-block should fix this, however, this would require implementing AutoClosable for JarFileModule. This code was batch refactored in https://github.com/wala/WALA/commit/b1678882b399924b46a127c29143d223254969dc but it apparently hasn't been tested for side effects. A quick fix would be to revert it to the old, potentially leaking, implementation:

`scope.addToScope(ClassLoaderReference.Primordial, new JarFileModule(new JarFile(new File(al))));
`
While fixing this, maybe re-checking the aforementioned refactoring commit for other potential side-effects would be desired. Any suggestions on this?

### PR DESCRIPTION
**Pull request by reddr**
Fixes #355 

Reverts refactored code with try-with-resource back to potentially
leaking implementation. The refactored code threw an exception since
JarFileModule does not implement the AutoClosable interface. Further,
removed the printStackTrace() call, as this is not an exceptional case
but intended control-flow in case DexFileModule creation fails.

### CODE REVIEW

**Comment by reddr** [comment]
Hmm, the CI failed for Linux but passed on Mac (gradle build passed on my Mac as well).
On Linux, it seems that some wala.core testcases failed, which is kind of suprising since the patch should only affect the wala.dalvik. 

Anyone thoughts on this?

**Comment by msridhar** [comment]
@liblit I think this change is now failing an ECJ compiler check on Travis that we made into an error.  Can you advise on how to suppress the warning?

**Comment by liblit** [comment]
ECJ gets its diagnostic configuration from Eclipse. If this is failing with a compilation error in Travis CI, then there must also be an error message in Eclipse. Fix or downgrade that error in Eclipse and the ECJ build in Travis CI should pass too.

If you are not seeing such an error in Eclipse, then use “Project → Clean…” to force Eclipse to rebuild. I did that with the code from this pull request and the error appeared in Eclipse’s “Problems” view a few seconds later.

I recommend downgrading this error to a warning, since that is how we already treat other `JarFile` leaks. Right-click on the error and choose “Quick Fix”. Among the quick fixes offered, choose “Configure problem severity”. You should now see a window box with options for setting the severity of various potential problems, with “Potential resource leak:” already selected. Change the setting for “Potential resource leak:” from “Error” to “Warning”.

**Comment by msridhar** [comment]
@reddr are you set up with Eclipse so you can make the change @liblit suggests?

**Comment by reddr** [comment]
@msridhar currently I'm not, but will try to set it up this week

**Comment by liblit** [comment]
@reddr, would you prefer that I clone *your* WALA repo, apply the recommended Eclipse configuration change, and offer that back to you as a pull request? Accepting that into your `jarfilemodule` branch should then update *this* pull request accordingly.

**Comment by liblit** [comment]
[Done](https://github.com/reddr/WALA/pull/1).

**Comment by msridhar** [comment]
Merged, thanks!

**Pull request merged**
