### PR TITLE
Fix Buildship import for Eclipse running on JRE > 8

### PR DESCRIPTION
**Pull request by khatchad**
This PR serves as an alternative to https://github.com/wala/WALA/pull/732. Here, we continue to use Buildship but explicitly specify the source and target compatibilities so that it imports correctly in Eclipse using JRE >= 9.

I still get the following non-Java build errors but per https://github.com/wala/WALA/pull/732#issuecomment-604785008 they may require separate investigations:

Description | Resource | Path | Location | Type
-- | -- | -- | -- | --
'source.target/dependency/com.ibm.wala.cast.jar' build entry is missing | build.properties | /com.ibm.wala.ide | line 1 | Plug-in Problem
'source.target/dependency/com.ibm.wala.core.jar' build entry is missing | build.properties | /com.ibm.wala.ide | line 1 | Plug-in Problem
'source.target/dependency/com.ibm.wala.shrike.jar' build entry is missing | build.properties | /com.ibm.wala.ide | line 1 | Plug-in Problem
'source.target/dependency/com.ibm.wala.util.jar' build entry is missing | build.properties | /com.ibm.wala.ide | line 1 | Plug-in Problem
build.properties does not exist | com.ibm.wala.cast.java |  | Unknown | Plug-in Problem
Package 'com.ibm.wala.analysis.arraybounds.hypergraph.algorithms' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 49 | Plug-in Problem
Package 'com.ibm.wala.analysis.arraybounds.hypergraph.weight.edgeweights' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 51 | Plug-in Problem
Package 'com.ibm.wala.analysis.arraybounds.hypergraph.weight' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 50 | Plug-in Problem
Package 'com.ibm.wala.analysis.arraybounds.hypergraph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 48 | Plug-in Problem
Package 'com.ibm.wala.analysis.arraybounds' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 47 | Plug-in Problem
Package 'com.ibm.wala.analysis.exceptionanalysis' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 52 | Plug-in Problem
Package 'com.ibm.wala.analysis.nullpointer' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 53 | Plug-in Problem
Package 'com.ibm.wala.analysis.pointers' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 54 | Plug-in Problem
Package 'com.ibm.wala.analysis.reflection.java7' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 56 | Plug-in Problem
Package 'com.ibm.wala.analysis.reflection' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 55 | Plug-in Problem
Package 'com.ibm.wala.analysis.stackMachine' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 57 | Plug-in Problem
Package 'com.ibm.wala.analysis.typeInference' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 58 | Plug-in Problem
Package 'com.ibm.wala.cast.analysis.typeInference' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 119 | Plug-in Problem
Package 'com.ibm.wala.cast.ipa.callgraph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 120 | Plug-in Problem
Package 'com.ibm.wala.cast.ipa.cha' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 121 | Plug-in Problem
Package 'com.ibm.wala.cast.ipa.lexical' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 122 | Plug-in Problem
Package 'com.ibm.wala.cast.ipa.modref' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 123 | Plug-in Problem
Package 'com.ibm.wala.cast.ir.cfg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 124 | Plug-in Problem
Package 'com.ibm.wala.cast.ir.ssa.analysis' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 126 | Plug-in Problem
Package 'com.ibm.wala.cast.ir.ssa' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 125 | Plug-in Problem
Package 'com.ibm.wala.cast.ir.translator' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 127 | Plug-in Problem
Package 'com.ibm.wala.cast.loader' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 128 | Plug-in Problem
Package 'com.ibm.wala.cast.tree.impl' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 130 | Plug-in Problem
Package 'com.ibm.wala.cast.tree.pattern' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 131 | Plug-in Problem
Package 'com.ibm.wala.cast.tree.rewrite' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 132 | Plug-in Problem
Package 'com.ibm.wala.cast.tree.visit' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 133 | Plug-in Problem
Package 'com.ibm.wala.cast.tree' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 129 | Plug-in Problem
Package 'com.ibm.wala.cast.types' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 134 | Plug-in Problem
Package 'com.ibm.wala.cast.util.test' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 136 | Plug-in Problem
Package 'com.ibm.wala.cast.util' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 135 | Plug-in Problem
Package 'com.ibm.wala.cfg.cdg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 60 | Plug-in Problem
Package 'com.ibm.wala.cfg.exc.inter' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 62 | Plug-in Problem
Package 'com.ibm.wala.cfg.exc.intra' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 63 | Plug-in Problem
Package 'com.ibm.wala.cfg.exc' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 61 | Plug-in Problem
Package 'com.ibm.wala.cfg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 59 | Plug-in Problem
Package 'com.ibm.wala.classLoader' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 64 | Plug-in Problem
Package 'com.ibm.wala.client' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 65 | Plug-in Problem
Package 'com.ibm.wala.core.plugin' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 68 | Plug-in Problem
Package 'com.ibm.wala.core.tests.callGraph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 66 | Plug-in Problem
Package 'com.ibm.wala.core.tests.util' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 67 | Plug-in Problem
Package 'com.ibm.wala.dataflow.graph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 27 | Plug-in Problem
Package 'com.ibm.wala.dataflow.IFDS' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 69 | Plug-in Problem
Package 'com.ibm.wala.dataflow.ssa' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 70 | Plug-in Problem
Package 'com.ibm.wala.demandpa.alg.refinepolicy' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 72 | Plug-in Problem
Package 'com.ibm.wala.demandpa.alg.statemachine' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 73 | Plug-in Problem
Package 'com.ibm.wala.demandpa.alg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 71 | Plug-in Problem
Package 'com.ibm.wala.demandpa.flowgraph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 74 | Plug-in Problem
Package 'com.ibm.wala.demandpa.util' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 75 | Plug-in Problem
Package 'com.ibm.wala.escape' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 76 | Plug-in Problem
Package 'com.ibm.wala.examples.analysis.dataflow' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 77 | Plug-in Problem
Package 'com.ibm.wala.examples.drivers' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 78 | Plug-in Problem
Package 'com.ibm.wala.examples.properties' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 79 | Plug-in Problem
Package 'com.ibm.wala.fixedpoint.impl' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 28 | Plug-in Problem
Package 'com.ibm.wala.fixpoint' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 29 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.cha' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 81 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.impl' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 82 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.propagation.cfa' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 85 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.propagation.rta' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 86 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.propagation' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 84 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.pruned' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 87 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph.util' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 83 | Plug-in Problem
Package 'com.ibm.wala.ipa.callgraph' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 80 | Plug-in Problem
Package 'com.ibm.wala.ipa.cfg.exceptionpruning.filter' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 90 | Plug-in Problem
Package 'com.ibm.wala.ipa.cfg.exceptionpruning.interprocedural' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 91 | Plug-in Problem
Package 'com.ibm.wala.ipa.cfg.exceptionpruning' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 89 | Plug-in Problem
Package 'com.ibm.wala.ipa.cfg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 88 | Plug-in Problem
Package 'com.ibm.wala.ipa.cha' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 92 | Plug-in Problem
Package 'com.ibm.wala.ipa.modref' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 93 | Plug-in Problem
Package 'com.ibm.wala.ipa.slicer.thin' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 95 | Plug-in Problem
Package 'com.ibm.wala.ipa.slicer' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 94 | Plug-in Problem
Package 'com.ibm.wala.ipa.summaries' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 96 | Plug-in Problem
Package 'com.ibm.wala.model.java.lang.reflect' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 99 | Plug-in Problem
Package 'com.ibm.wala.model.java.lang' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 98 | Plug-in Problem
Package 'com.ibm.wala.model' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 97 | Plug-in Problem
Package 'com.ibm.wala.properties' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 100 | Plug-in Problem
Package 'com.ibm.wala.shrike.bench' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 139 | Plug-in Problem
Package 'com.ibm.wala.shrike.cg' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 140 | Plug-in Problem
Package 'com.ibm.wala.shrike.copywriter' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 141 | Plug-in Problem
Package 'com.ibm.wala.shrike.instrumentation' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 142 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT.analysis' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 144 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT.info' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 145 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT.shrikeCT.tools' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 147 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT.shrikeCT' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 146 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT.tools' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 148 | Plug-in Problem
Package 'com.ibm.wala.shrikeBT' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 143 | Plug-in Problem
Package 'com.ibm.wala.shrikeCT' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 149 | Plug-in Problem
Package 'com.ibm.wala.sourcepos' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 22 | Plug-in Problem
Package 'com.ibm.wala.ssa.analysis' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 102 | Plug-in Problem
Package 'com.ibm.wala.ssa' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 101 | Plug-in Problem
Package 'com.ibm.wala.types.annotations' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 104 | Plug-in Problem
Package 'com.ibm.wala.types.generics' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 105 | Plug-in Problem
Package 'com.ibm.wala.types' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 103 | Plug-in Problem
Package 'com.ibm.wala.util.bytecode' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 107 | Plug-in Problem
Package 'com.ibm.wala.util.collections' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 31 | Plug-in Problem
Package 'com.ibm.wala.util.config' does not exist in this plug-in | MANIFEST.MF | /com.ibm.wala.ide/META-INF | line 32 | Plug-in Problem

### CODE REVIEW

**Comment by liblit** [comment]
@khatchad wrote:
> I still get the following non-Java build errors but per #732 (comment) they may require separate investigations:

Agreed: we should investigate those separately. See [this comment](https://github.com/wala/WALA/pull/732#issuecomment-605358230) for my current hypothesis and recommended next steps. Let's move any further discussion of these plugin errors into a new issue.

**Comment by liblit** [comment]
GitHub's page for this pull request claims that the Travis CI build is still in progress. But Travis CI itself shows all jobs completed without error. I'm going to trust Travis CI's report about its own status and consider this to be passing all CI tests. Yay!

Thanks for this contribution, @khatchad. I know I was hard to convince, but I believe this is all resulting in an improved understanding of what's going on and how to manage it all better in the future. I appreciate the role you have played in that.

**Comment by liblit** [comment]
Although not mentioned in commit messages, this pull request fixed #731.

**Comment by khatchad** [comment]
> Although not mentioned in commit messages, this pull request fixed #731.

Thanks for all your help @liblit and @msridhar! Regarding #731, I should document that [clearing `GRADLE_HOME` in the Eclipse settings ultimately got this working](https://github.com/wala/WALA/issues/731#issuecomment-604465043). This was strange because the variable is set correctly, but there is some odd warning in Eclipse about setting this variable for some reason.

**Pull request merged**
