### PR TITLE
Allow AnalysisScopeReader to ingest WAR files.

### PR DESCRIPTION
**Pull request by collinw**
The motivating use-case is building a whole-program call graph for web
apps packaged into WAR files.

### CODE REVIEW

**Comment by juliandolby** [comment]
Collin,

  Don't WAR files have a different structure, with code in a WEB-INF
directory?  In general, handling war files would be nice, and I will be
happy to merge this change if you can also provide a test case of handling
a war.

	-- Julian

**Comment by collinw** [comment]
Yes, WAR files have a different structure. Here's the structure of a WAR file for a sample Google App Engine app:

"""
Archive:  /tmp/guestbook-1.0-SNAPSHOT.war
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF    
   creating: stylesheets/
   creating: WEB-INF/
   creating: WEB-INF/classes/
   creating: WEB-INF/classes/com/
   creating: WEB-INF/classes/com/example/
   creating: WEB-INF/classes/com/example/guestbook/
   creating: WEB-INF/lib/
  inflating: guestbook.jsp           
  inflating: stylesheets/main.css    
  inflating: WEB-INF/appengine-web.xml  
  inflating: WEB-INF/classes/com/example/guestbook/Greeting.class  
  inflating: WEB-INF/classes/com/example/guestbook/Guestbook.class  
  inflating: WEB-INF/classes/com/example/guestbook/GuestbookServlet.class  
  inflating: WEB-INF/classes/com/example/guestbook/OfyHelper.class  
  inflating: WEB-INF/classes/com/example/guestbook/SignGuestbookServlet.class  
  inflating: WEB-INF/lib/appengine-api-1.0-sdk-1.9.18.jar  
  inflating: WEB-INF/lib/guava-18.0.jar  
  inflating: WEB-INF/lib/jstl-1.2.jar  
  inflating: WEB-INF/lib/objectify-5.1.5.jar  
  inflating: WEB-INF/logging.properties  
  inflating: WEB-INF/web.xml         
  inflating: META-INF/maven/com.example.guestbook/guestbook/pom.xml  
  inflating: META-INF/maven/com.example.guestbook/guestbook/pom.properties
"""

ClassLoaderImpl.getClassFiles() already contains logic for recursing through jar files (and, actually, war files), discarding anything unexpected. That's why this pull request was the only change I needed to make to be able to analyze a war file. You can see this in action if you set ClassLoaderImpl.DEBUG=1:

"""
Ignoring entry: guestbook-1.0-SNAPSHOT.war:guestbook.jsp
Ignoring entry: guestbook-1.0-SNAPSHOT.war:META-INF/
Ignoring entry: guestbook-1.0-SNAPSHOT.war:stylesheets/main.css
Ignoring entry: guestbook-1.0-SNAPSHOT.war:WEB-INF/classes/com/example/
Ignoring entry: guestbook-1.0-SNAPSHOT.war:META-INF/MANIFEST.MF
Ignoring entry: guestbook-1.0-SNAPSHOT.war:META-INF/maven/com.example.guestbook/guestbook/pom.properties
Ignoring entry: guestbook-1.0-SNAPSHOT.war:WEB-INF/lib/
Ignoring entry: guestbook-1.0-SNAPSHOT.war:WEB-INF/logging.properties
"""

I'm happy to add a test. Looking through com.ibm.wala.core.tests, I didn't see any existing tests for AnalysisScopeReader; did I miss them, or should I create a new test file under com.ibm.wala.core.tests/src/com/ibm/wala/util/config/?

**Comment by juliandolby** [comment]
It would be great if you could add to CallGraphTests, putting in a test
that reads a scope with a .war file and looks at the call graphs.  Ideally,
it would be nice to also have a test that just creates a class hierarchy
and asserts the existence of some expected classes.

	-- Julian

**Comment by collinw** [comment]
Thanks, I've added a test, and it caught a problem that I've addressed in the same commit. I had previously only been validating that a class hierarchy could be generated, not that the contents were correct.

Please take a look.

**Comment by juliandolby** [comment]
Collin,

  Thanks, this looks good.  Having the test check that a class really gets
loaded is nice.

  One last issue.  Since WALA is dual-use technology---github project and
IBM product---we need to be careful about the files we include in the
master.  Could you please tell me where the guestbook.war file originated?
If it is some kind of example code or standard benchmark, then it would be
ideal if we set up the scripts to download it rather than committing it to
the repository.  For some examples of how this is done, take a look at how
jlex, java_cup and bcel are downloaded in com.ibm.core.testdata/build.xml.

 Sorry to be a pain about that, but if we are careful, we can keep WALA
being useful both for IBM and for everyone else.

	Thanks,
		Julian

**Comment by collinw** [comment]
guestbook.war comes from a sample Google App Engine guestbook app: https://github.com/GoogleCloudPlatform/appengine-java-guestbook-multiphase, commit 71e38b0d612677bd4bdb6fbea75989104d5b3248. I built the war file from that project, then stripped out most of the files (the GAE SDK, a copy of Guava, etc) to reduce the size from 17MB to 11K. The sample code is available under the Apache 2.0 license.

I've added a LICENSE file to guestbook.war with the text of the license, as well as a README file that describes where it came from.

Building the war file as part of the build process would be tricky, since it requires a different version of Maven than WALA. If Apache 2.0 isn't acceptable, I could build a new war file myself and license it under EPL for use in WALA.

**Comment by collinw** [comment]
Friendly ping. Is guestbook.war acceptable as-is under the Apache 2.0 license, or should I build a new one from scratch?

**Comment by juliandolby** [comment]
Collin,

  Sorry, but it is going to be much easier for us if you can create a .war
file from scratch.

	Thanks,
		Julian

**Comment by msridhar** [comment]
@collinw as a bit more explanation, independent of the license on the guestbook app, IBM requires vetting of things like authorship for any third-party open-source code before allowing it to be shipped in IBM products.  If you build a new test case from scratch, then there will be a "paper trail" that you authored the code and contributed it to WALA under appropriate terms, which avoids the need for this vetting.

**Comment by msridhar** [comment]
@collinw do you still think you might be able to make this contribution? Otherwise we will close this PR. Thanks!

**Pull request closed without merging**
