### PR TITLE
Eliminate all Eclipse XML validation warnings

### PR DESCRIPTION
**Pull request by liblit**
Before this set of changes, all XML validation warnings concerned the lack of grammar constraints in XML documents that have no DTD or XML Schema declarations. For XML documents in third-party components, we are not in a position to do anything about that. Therefore, we now exclude those documents from XML validation entirely. We also exclude certain XML documents that are generated by third-party tools, since these too are outside of our control.

For XML documents that we do control, I have added stub DTD declarations (e.g., `<!DOCTYPE project>`). Obviously that does not provide a full, checkable document grammar. It is enough, though, to satisfy Eclipse's XML validator and remove the grammar constraints warnings.

### CODE REVIEW

**Comment by liblit** [comment]
[The Travis CI failure](https://travis-ci.org/wala/WALA/builds/179579150#L233) is an intermittent problem unrelated to these changes: 

> "/home/travis/build/wala/WALA/com.ibm.wala.core.testdata/build.xml:83: Can't get http://archive.apache.org/dist/jakarta/bcel/binaries/bcel-5.2.tar.gz to /home/travis/build/wala/WALA/com.ibm.wala.core.testdata/temp.folder/bcel-5.2.tar.gz".

I recommend telling Travis to restart the test. In my copy of this branch, I had to restart the test twice earlier today before [it finally succeeded](https://travis-ci.org/liblit/WALA/builds/179569054).

**Comment by msridhar** [comment]
@liblit I merged #112 but now this PR is shown as having conflicts.  Could you possibly fix things up so the PR applies cleanly to the new master?

Thanks again for these cleanup patches!

**Comment by liblit** [comment]
I have merged with the latest master and resolved any conflicts. Travis CI is showing the [same intermittent failure](https://travis-ci.org/wala/WALA/builds/179808280#L232) as before, though. I recommend restarting the Travis build. That being said, I have restarted my own Travis build three times already and it is [still failing in the same way](https://travis-ci.org/liblit/WALA/builds/179808278#L222). It doesn’t seem that my changes could have caused this failure, but I just don’t know what’s going wrong here for sure.

**Comment by msridhar** [comment]
Finally got a passing test run. Thanks again!

**Comment by liblit** [comment]
You’re welcome!

I wish I knew what was causing those Travis-CI failures. So far, it still does not seem to be the result of any changes I made. My fault or not, though, it is certainly an impediment to progress.

**Pull request merged**
