### PR TITLE
Update to Error Prone 2.17.0

### PR DESCRIPTION
**Pull request by msridhar**
Just to keep up

### CODE REVIEW

**Review by liblit — APPROVED** [review]

**Comment by msridhar** [comment]
This is a bit weird:

https://github.com/wala/WALA/actions/runs/3809918658/jobs/6481638942#step:5:500

Somehow, for the CI job for this change, we get a build cache hit for `:com.ibm.wala.core:test`, even though `:com.ibm.wala.core:compileJava` and `:com.ibm.wala.core:testClasses` had to re-build.  @liblit does this look suspicious to you?

**Comment by msridhar** [comment]
It's possible there is some special logic in the Gradle ErrorProne plugin that tells Gradle that even though the code needs to be re-compiled, the tests don't need to run as there is no semantic change?  I can look into that.  Want to understand before landing this.

**Comment by liblit** [comment]
> It's possible there is some special logic in the Gradle ErrorProne plugin that tells Gradle that even though the code needs to be re-compiled, the tests don't need to run as there is no semantic change?

Gradle's caching logic is fairly fancy, with plenty of opportunities to leverage alternate (e.g., semantic) definitions for equivalence. See [Better reuse via input normalization](https://docs.gradle.org/current/userguide/build_cache_concepts.html#normalization). I am inclined to trust that Gradle did the right thing here.

**Comment by msridhar** [comment]
> Gradle's caching logic is fairly fancy, with plenty of opportunities to leverage alternate (e.g., semantic) definitions of equivalence. See [Better reuse via input normalization](https://docs.gradle.org/current/userguide/build_cache_concepts.html#normalization). I am inclined to trust that Gradle did the right thing here.

Oh, I get it!  The thing here is that even though the compile tasks re-ran, the output _bytecodes_ were identical.  So, no need to re-run the tests, as the inputs are the same!  Very clever.  I am satisfied 🙂

**Comment by liblit** [comment]
We've come a long way since the days of the Maven build, where the only trustworthy build was a clean rebuild, eh? :brain:

**Pull request merged**
