### PR TITLE
AnalysisCache -> IAnalysisCache, additional ignore, increased visibility, generic fixes

### PR DESCRIPTION
**Pull request by khatchad**
- Fixed compile-time errors for the move to `IAnalysisCache` from `AnalysisCache`.
- Ignore the `results` directory that is created by default.
- Increased visibility for some methods in `CallString`. These were useful for an extension.
- Generic type fixes in `ModRef.java`.

### CODE REVIEW

**Comment by msridhar** [comment]
@khatchad LGTM, but can you rebase and fix the conflicts?

**Comment by khatchad** [comment]
@msridhar Sorry about that. How's this?

**Comment by khatchad** [comment]
Oh hold up. Have a build failure.

**Comment by khatchad** [comment]
Should be okay now.

**Comment by msridhar** [comment]
Thanks!

**Pull request merged**
