### PR TITLE
Avoid conditional dependencies

### PR DESCRIPTION
**Pull request by liblit**
Gradle dependency version locksets work best when dependencies are fixed
across all builds.

### CODE REVIEW

**Comment by msridhar** [comment]
The CI failure is due to a flaky test (#916).  A restart should hopefully fix.

I'm really puzzled by this issue.  I'd like to think a bit more about what could be the root cause before approving.

**Comment by msridhar** [comment]
It seems the `-PexcludeSlowTests` flag is related to / causing this issue, at least that's what I see locally.  @liblit can you confirm that if you remove that option you don't get the same type of failure anymore?  I wonder if that property is causing additional dependencies to be pulled in.  If so, maybe it'd be better to pull in the deps unconditionally somehow?  If that's too tricky, I'm ok with this current fix, with some extra comments indicating why we need it.

**Comment by liblit** [comment]
> It seems the `-PexcludeSlowTests` flag is related to / causing this issue, at least that's what I see locally.

Woah. 🤯 How did you manage to figure that out?

> @liblit can you confirm that if you remove that option you don't get the same type of failure anymore?

Confirmed.

> I wonder if that property is causing additional dependencies to be pulled in.

It must have something to do with this code that only executes when `excludeSlowTests` is set:

https://github.com/wala/WALA/blob/35b8e41f230abb6062a9a66c2f6c7ae4611036d2/build.gradle#L113-L115

> If so, maybe it'd be better to pull in the deps unconditionally somehow?

Indeed, I think that's exactly the right solution, rather than the workaround-without-true-understanding that I originally proposed here. I'll revise the code and this pull request accordingly. Good job, @msridhar!

**Review by msridhar — APPROVED** [review]
👍

**Comment by liblit** [comment]
@msridhar wrote:
> The CI failure is due to a flaky test (#916). A restart should hopefully fix.

Thanks for that hint, too. I would have spent a nontrivial amount of time rediscovering that on my own.

**Pull request merged**
