### PR TITLE
Fix Eclipse warnings relating to `switch` statements

### PR DESCRIPTION
**Pull request by liblit**
This pull request covers a variety of Eclipse complaints relating to `switch` statements. Generally we are adding `default` cases where there were none, adding specific `case` entries to match previously-unmatched `enum` values, and/or tidying up fall-through flows of control. Each individual commit contains either a single unusual fix or a group of fixes that apply the same general approach to all affected statements; see the individual commit messages for details.

### CODE REVIEW

**Comment by msridhar** [comment]
@liblit I generally prefer the rebase and merge strategy for pull requests to keep a linear commit history, but GitHub is telling me that this strategy won't work here.  Could you possibly take a look?  I think the thing to do is just run `git rebase master` from your branch, and hopefully things will work out.

**Comment by liblit** [comment]
@msridhar: OK, I have rebased this pull request and manually fixed up some merge conflicts with Julian’s 6cdeedd5e99e508447163997fba5af289447e6a9 commit. Travis-CI still gives this pull request a [green light](https://travis-ci.org/wala/WALA/builds/264861645) after the rebase.

**Comment by msridhar** [comment]
Thanks @liblit!

**Comment by liblit** [comment]
You are most welcome, @msridhar!

**Pull request merged**
