### PR TITLE
Remove -Wall compiler flag

### PR DESCRIPTION
**Pull request by khatchad**
I had to make this change to get the builship import to work.

### CODE REVIEW

**Comment by khatchad** [comment]
Now I'm seeing in the buld a bunch of warnings pertaining to test code, which probably isn't what we want.

**Comment by khatchad** [comment]
My feeling is that buidhship isn't properly working here, and the only viable way to import WALA into Eclipse is through using `./gradlew eclipse`.

**Comment by khatchad** [comment]
And even `./gradlew eclipse` doesn't completely work. It still needs some finagling to get it building.

**Comment by msridhar** [comment]
Thanks for all the digging @khatchad.  If you have time to update our docs on what is necessary here that would be much appreciated.

**Pull request closed without merging**
