### PR TITLE
[WIP] Fix M1 Mac configuration issue

### PR DESCRIPTION
**Pull request by msridhar**
It seems the latest Gradle update broke configuration on M1 Macs.  I was attempting to fix but got stuck.  I added an M1 Mac to the CI config so we catch this in the future hopefully.

### CODE REVIEW

**Comment by msridhar** [comment]
@liblit you can see the configuration error that occurs here:

https://github.com/wala/WALA/actions/runs/8470614425/job/23208719124?pr=1383#step:7:129

I tried to fix this by adding these lines around line 42 of `cast/smoke_main/build.gradle.kts`:

```
// Dynamically determine the architecture string
val architectureName = rootProject.extra["archName"] as String
attribute(Attribute.of("org.gradle.native.architecture", String::class.java), architectureName)
```

But this broke config on other platforms, and it led to a new issue on M1 Macs (I got some message about duplicate tasks named `checkSmokeMain`).  I'm wondering if you might have time to take a look at this?  I am blocked from basically doing anything with WALA on my local laptop until we fix this without downgrading Gradle locally or something like that.

**Comment by msridhar** [comment]
Also note that I don't really care if I can build the native code stuff on an M1 Mac, but I do need configuration to succeed :-)

**Comment by liblit** [comment]
> I'm wondering if you might have time to take a look at this?

Yes, I can dive in. Perhaps as soon as today, but perhaps as late as this coming weekend.

> I am blocked from basically doing anything with WALA on my local laptop until we fix this without downgrading Gradle locally or something like that.

Please feel free to revert that Gradle upgrade until I can get it working for M1 too. I don't want you to be blocked waiting for me to fix this.

**Comment by msridhar** [comment]
Another note: `:cast:cast:linkRelease` and `:cast:cast:linkDebug` were already failing on my M1 Mac before the Gradle upgrade.  It's not critical to me that they succeed.  We could exclude those tasks on the M1 Mac CI job if needed.

**Comment by liblit** [comment]
Solved by #1387.

**Pull request closed without merging**
