### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by msridhar**
Limited to what seemed like "safe" updates that I don't expect to cause test failures.

### CODE REVIEW

**Review by liblit — APPROVED** [review]
Approved, but it looks like the macOS build needs to be restarted after a temporary network outage.

**Comment by msridhar** [comment]
@liblit I think I made the failed download more reliable by switching to https. Can I get another review? I'll do a follow up where I search for other download URLs that we should switch.

**Comment by liblit** [comment]
> @liblit I think I made the failed download more reliable by switching to https.

If I remember correctly, the failed build was reporting "no route to host" or something along those lines.  That's a failure down at the level of IP routing: below TCP and below application protocols like HTTP or HTTPS.  I see no reason why switching to HTTPS would improve reliability.  More likely you just got luckier with the retry, as we've seen with many other transient network outages in our GitHub actions.

**Comment by msridhar** [comment]
> If I remember correctly, the failed build was reporting "no route to host" or something along those lines. That's a failure down at the level of IP routing: below TCP and below application protocols like HTTP or HTTPS. I see no reason why switching to HTTPS would improve reliability. More likely you just got luckier with the retry, as we've seen with many other transient network outages in our GitHub actions.

Looks like you may have been right.  I still think the HTTPS change is a good one, but I can do that in a separate PR.  If you could re-stamp the original set of changes that would be great :-)

**Review by liblit — APPROVED** [review]

**Comment by liblit** [comment]
> I still think the HTTPS change is a good one, but I can do that in a separate PR.

No objection from me. I'll point out, though, that we verify downloads' signatures against expectations. So even with HTTP, we are fairly safe from men-in-the-middle.

**Pull request merged**
