### PR TITLE
Remove JUnit 4 dependency

### PR DESCRIPTION
**Pull request by liblit**
All tests and test infrastructure have been migrated or ported to JUnit 5. Nothing remains that uses JUnit 4.

### CODE REVIEW

**Comment by msridhar** [comment]
Shall we double check that the test numbers match in the report before merging this one?  Or is it guaranteed safe as long as the test code compiles?

**Comment by liblit** [comment]
No harm waiting to review the test summary. We need to wait until the "Continuous integration" runs finish anyway, and the report is produced immediately after that.

**Comment by msridhar** [comment]
> No harm waiting to review the test summary. We need to wait until the "Continuous integration" runs finish anyway, and the report is produced immediately after that.

The PR was set to auto-merge, so I was wondering if with an approving review the change would get merged independent of the test report contents, as long as the tests passed (which may not be what we want).

**Comment by liblit** [comment]
Good point. I've turned off auto-merge. You can review and approve more, or at your convenience. I'll postpone merging until I've looked over the test report.

**Review by msridhar — APPROVED** [review]

**Pull request merged**
