### PR TITLE
Add ZeroOneCFABuilderFactory

### PR DESCRIPTION
**Pull request by linghuiluo**

### CODE REVIEW

**Comment by linghuiluo** [comment]
@juliandolby as we talked about yesterday

**Comment by juliandolby** [comment]
can we run ./gradlew verifyGoogleJavaFormat on this code?  the travis checks seem to be complaining.

**Comment by msridhar** [comment]
I think you want `./gradlew goJF` to actually format the code

**Comment by linghuiluo** [comment]
@juliandolby now checks passed

**Pull request merged**
