### PR TITLE
Remove JUnit as an implementation dependence of cast.js

### PR DESCRIPTION
**Pull request by msridhar**
JUnit should only be required for tests.

### CODE REVIEW

**Comment by liblit** [comment]
Two CI tests failed with what look like transient network problems. I've restarted the CI test site.

**Comment by liblit** [comment]
Hmm, still failing. I'm not sure what broke here.

**Comment by msridhar** [comment]
The alfresco Maven repo that we pull WSDT artifacts from is flaky. I've seen this before. Hopefully it'll fix itself in a bit.

**Review by liblit — APPROVED** [review]
I'm approving this now, but please do not merge to `master` until all tests are passing.

**Pull request merged**
