### PR TITLE
Enable Eclipse Oxygen’s new “unlikely argument types” diagnostics

### PR DESCRIPTION
**Pull request by liblit**
Eclipse Oxygen offers [two new diagnostics](https://www.eclipse.org/eclipse/news/4.7/jdt.php#unlikely-argument-types) for situations where argument types are strictly correct, but unlikely to be what the programmer intended. One of these diagnostics covers various collection methods, and the other covers `Object.equals()`.  For each of these diagnostics, I’ve set the severity level to “warning” in projects that have some instances of the suspicious code, or to “error” in projects that have no instances of the suspicious code.

I am pleased to report that no other changes were needed to get WALA up and running under Eclipse Oxygen. That’s a nice change from the porting work we had to do for [Neon](https://github.com/wala/WALA/pull/103), [Mars](https://github.com/wala/WALA/issues/98), and [Luna](https://github.com/wala/WALA/issues/56).

### CODE REVIEW

**Comment by msridhar** [comment]
@liblit have you had a chance to inspect the warnings at all? Also, I am unclear about what ECJ compiler version is used by Tycho. Could you check if introducing an error here actually causes a Maven / Travis build failure?

**Comment by liblit** [comment]
@msridhar, yes I have looked at the warnings. There are only four, one of which appears twice. In my judgement, all four point out code that likely does not do what its authors intended:

Occurrences|Problem Description|My Opinion
-|-|-
2|Unlikely argument type `CAstNode` for `containsKey(Object)` on a `Map<Pair<CAstNode,CAstBasicRewriter.NoKey>,CAstNode>`|The warning seems valid; the code seems wrong. The given map will never contain any `CAstNode` as a key, because the map's keys are always `Pair<...>`. The code in question is asserting non-containment, so that `assert` will always succeed, but surely is not checking what the author intended to check.
1|Unlikely argument type `Integer` for `remove(Object)` on a `Collection<HyperNode<Integer>>`|The warning seems valid; the code seems wrong. The removal will always fail, because we are trying to remove an `Integer` from a collection of `HyperNode<Integer>`. I am not sure what the author intended, but this doesn't seem right.
1|Unlikely argument type `TypeName` for `get(Object)` on a `Map<String,String>`|The warning seems valid; the code seems wrong. The `get` will always fail, because `TypeName` is not a `String` and the map only contains items keyed by `String`. As in the first row of this table, the code in question is asserting that the `get` fails, which it always will. But surely this is not what the author intended to check.

Regarding which ECJ compiler version is used by Tycho, I am also confused about this. I raised the severity of the above from warnings to errors, then ran `mvn clean install -DskipTests`. To my surprise, this succeeded, even though the Eclipse GUI was definitely showing four errors. So I do not completely understand how Tycho, ECJ, and the Eclipse GUI interact, and in what ways their diagnostics configurations are shared or not.

**Comment by msridhar** [comment]
Re: Tycho and ECJ, I think we need to set the [target platform](https://wiki.eclipse.org/Tycho/Target_Platform); not sure what it's set to now.  I'm a bit hesitant to bump the target platform to Eclipse Oxygen so soon after release.  @juliandolby are there any IBM constraints around Eclipse target platform version?

**Comment by liblit** [comment]
I am not sure whether changing the target platform would cause Tycho to report errors where Eclipse is configured to do so. I would try this out to see what happens if I could figure out how, but I cannot make sense of that documentation.

Either way, I think there is no harm in enabling these errors while not changing the target platform to Oxygen. Older Eclipse releases should just quietly ignore the settings for diagnostics they do not understand, while those of us using Oxygen will benefit from the additional checks.

**Comment by msridhar** [comment]
OK i'll merge. @liblit can you open an issue on updating the target platform in Tycho, so we don't forget?

**Comment by msridhar** [comment]
Also @liblit if there are obvious fixes for those warnings then fixes would be welcome ☺️

**Comment by liblit** [comment]
@msridhar, I prefer that you add the issue for target platform updating. I don't even understand what that means.

**Pull request merged**
